
import React, { useState, useEffect } from 'react';
import { Bot, FileCode, ArrowRight, Package, Check, Cloud, Loader2 } from 'lucide-react';
import { useAdmin } from '@/lib/AdminProvider';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';

const DockerBuilder = () => {
  const { agents, dockerActions, docker } = useAdmin();
  const { toast } = useToast();
  const [selectedAgent, setSelectedAgent] = useState(null);
  const [generatedDockerfile, setGeneratedDockerfile] = useState('');
  const [isBuilding, setIsBuilding] = useState(false);
  const [buildProgress, setBuildProgress] = useState(0);

  // Auto-Select first agent
  useEffect(() => {
     if (agents.length > 0 && !selectedAgent) setSelectedAgent(agents[0]);
  }, [agents]);

  // Generate Dockerfile when agent selected
  useEffect(() => {
     if (selectedAgent) {
        const dockerfile = `# Generated by Infinity X Agent Builder
FROM node:18-alpine
LABEL maintainer="infinity-x-admin"

# Agent: ${selectedAgent.name}
# Role: ${selectedAgent.role}

WORKDIR /app

# Install Dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy Agent Neural Weights & Code
COPY . .
ENV AGENT_ID="${selectedAgent.id}"
ENV AGENT_ROLE="${selectedAgent.role}"
ENV INFINITY_NET="enabled"

# Build Capabilities
${selectedAgent.capabilities.map(cap => `# Enable capability: ${cap}\nRUN npm run build:${cap}`).join('\n')}

EXPOSE 8080
CMD ["node", "agent-runner.js"]`;
        setGeneratedDockerfile(dockerfile);
     }
  }, [selectedAgent]);

  const handleBuild = () => {
     setIsBuilding(true);
     setBuildProgress(0);

     const interval = setInterval(() => {
        setBuildProgress(prev => {
           if (prev >= 100) {
              clearInterval(interval);
              return 100;
           }
           return prev + 10;
        });
     }, 300);

     setTimeout(() => {
        clearInterval(interval);
        setIsBuilding(false);
        const newImage = dockerActions.buildImage(`infinity/agent-${selectedAgent.id}:latest`, '245MB');
        toast({ title: "Build Complete", description: `Image ${newImage.tag} created successfully.` });
     }, 3500);
  };

  const handleCloudDeploy = async () => {
     toast({ title: "Cloud Run Deployment", description: "Initiating serverless deployment pipeline..." });
     await dockerActions.deployToCloudRun(`infinity/agent-${selectedAgent.id}:latest`);
     toast({ title: "Deployment Successful", description: "Agent is now live on Google Cloud Run." });
  };

  return (
    <div className="h-full flex gap-6">
       {/* Agent Selection Sidebar */}
       <div className="w-64 flex flex-col gap-2">
          <h3 className="text-xs font-bold uppercase text-gray-500 mb-2">Select Agent Source</h3>
          {agents.map(agent => (
             <div 
               key={agent.id}
               onClick={() => !isBuilding && setSelectedAgent(agent)}
               className={`p-3 rounded border cursor-pointer transition-all flex items-center gap-3 ${selectedAgent?.id === agent.id ? 'bg-[#0066FF]/20 border-[#0066FF] text-white' : 'bg-[#252526] border-white/5 text-gray-400 hover:bg-[#2a2d2e]'}`}
             >
                <Bot size={16} />
                <div className="truncate text-sm font-medium">{agent.name}</div>
             </div>
          ))}
       </div>

       {/* Builder Canvas */}
       <div className="flex-1 flex flex-col bg-[#1e1e1e] rounded-xl border border-white/10 overflow-hidden">
          <div className="p-4 border-b border-white/10 flex justify-between items-center bg-[#252526]">
             <div className="flex items-center gap-2">
                <FileCode size={18} className="text-blue-400" />
                <span className="font-mono text-sm">Dockerfile.generated</span>
             </div>
             <div className="flex gap-2">
                <Button 
                   size="sm" 
                   disabled={isBuilding}
                   onClick={handleBuild}
                   className="bg-[#0066FF] text-white gap-2"
                >
                   {isBuilding ? <Loader2 className="animate-spin" size={14} /> : <Package size={14} />}
                   {isBuilding ? 'Building...' : 'Build Image'}
                </Button>
                <Button 
                    size="sm"
                    variant="outline" 
                    onClick={handleCloudDeploy}
                    className="border-white/10 gap-2 hover:bg-white/5"
                >
                   <Cloud size={14} /> Deploy to Cloud
                </Button>
             </div>
          </div>

          <div className="flex-1 p-6 overflow-y-auto relative">
             <pre className="font-mono text-xs text-green-400 whitespace-pre-wrap">{generatedDockerfile}</pre>
             
             {isBuilding && (
                <div className="absolute inset-0 bg-black/80 flex flex-col items-center justify-center p-8">
                   <div className="w-full max-w-md space-y-2">
                      <div className="flex justify-between text-xs text-white">
                         <span>Building Context...</span>
                         <span>{buildProgress}%</span>
                      </div>
                      <div className="h-2 bg-white/10 rounded-full overflow-hidden">
                         <div className="h-full bg-blue-500 transition-all duration-300" style={{ width: `${buildProgress}%` }} />
                      </div>
                      <div className="h-32 bg-black rounded p-2 font-mono text-[10px] text-gray-400 overflow-y-auto mt-4">
                         {buildProgress > 10 && <div>[1/6] FROM node:18-alpine</div>}
                         {buildProgress > 25 && <div>[2/6] WORKDIR /app</div>}
                         {buildProgress > 40 && <div>[3/6] COPY package*.json ./</div>}
                         {buildProgress > 60 && <div>[4/6] RUN npm ci</div>}
                         {buildProgress > 80 && <div>[5/6] COPY . .</div>}
                         {buildProgress > 90 && <div>[6/6] EXPORTING LAYERS...</div>}
                      </div>
                   </div>
                </div>
             )}
          </div>
       </div>
    </div>
  );
};

export default DockerBuilder;
