"""
Documentor Agent: Documentation Generation

Write enterprise-grade docs, SOPs, design specs, chat logs, etc.
Automated documentation system.
"""

import os
from datetime import datetime


class DocumentorAgent:
    """
    DocumentorAgent: Generates documentation and records.

    Features:
    - Enterprise-grade documentation
    - SOP generation
    - Design specification writing
    - Meeting notes and chat logs
    - Markdown and JSON outputs
    """

    def __init__(self, config=None):
        """Initialize the documentor agent with optional configuration."""
        self.config = config or {}
        self.output_dir = config.get(
            "output_dir", "docs/output") if config else "docs/output"

    def document(self, validated, workspace):
        """
        Generate documentation and records from validated data.

        Args:
            validated: Validated data from ValidatorAgent
            workspace: Data workspace with context

        Returns:
            Dictionary with documentation paths and metadata
        """
        print("DocumentorAgent: Generating documentation and records...")

        # Write enterprise-grade docs, SOPs, design specs, chat logs, etc.
        result = {
            "timestamp": datetime.now().isoformat(),
            "documents": [],
            "status": "completed"
        }

        # Ensure output directory exists
        os.makedirs(self.output_dir, exist_ok=True)

        # Generate main documentation
        doc_path = self._generate_main_doc(validated, workspace)
        result["documents"].append(doc_path)

        # Generate summary report
        summary_path = self._generate_summary(validated)
        result["documents"].append(summary_path)

        # Generate metadata file
        metadata_path = self._generate_metadata(validated, workspace)
        result["documents"].append(metadata_path)

        print(f"DocumentorAgent: Generated {len(result['documents'])} "
              "documents")
        return result

    def _generate_main_doc(self, validated, workspace):
        """Generate the main documentation file."""
        path = os.path.join(self.output_dir, "auto_generated_doc.md")

        content = f"""# Auto-Generated Documentation

## Vision Cortex Run Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Validation Status:** {validated.get('status', 'unknown')}
**Quality Score:** {validated.get('quality_score', 0):.2f}

## Strategic Overview

{self._format_strategic_section(validated)}

## Data Organization

{self._format_organization_section(validated)}

## Quality Validation

{self._format_validation_section(validated)}

## Workspace Summary

- **Total Data Items:** {len(workspace.get('cleaned_data', []))}
- **Data Sources:** {len(workspace.get('raw_data', []))}
- **Status:** {workspace.get('status', 'unknown')}

## Recommendations

{self._format_recommendations(validated)}

---

*This document was automatically generated by the Vision Cortex system.*
"""

        with open(path, "w") as f:
            f.write(content)

        print(f"DocumentorAgent: Created {path}")
        return path

    def _generate_summary(self, validated):
        """Generate a summary report."""
        path = os.path.join(self.output_dir, "summary_report.md")

        data = validated.get("data", {})
        indexed_data = data.get("indexed_data", {})

        content = f"""# Vision Cortex Summary Report

**Date:** {datetime.now().strftime('%Y-%m-%d')}

## Executive Summary

The Vision Cortex multi-agent system has completed its analysis cycle.

### Key Metrics

- **Validation Status:** {validated.get('status', 'N/A')}
- **Quality Score:** {validated.get('quality_score', 0):.2f}
- **Data Categories:** {len(indexed_data.keys())}
- **Tags Applied:** {len(data.get('tags', []))}

### Strategic Data

{self._format_strategic_summary(indexed_data)}

### Next Steps

{chr(10).join('- ' + r for r in validated.get('recommendations', []))}

---

*Generated by DocumentorAgent*
"""

        with open(path, "w") as f:
            f.write(content)

        return path

    def _generate_metadata(self, validated, workspace):
        """Generate metadata JSON file."""
        import json

        path = os.path.join(self.output_dir, "metadata.json")

        metadata = {
            "timestamp": datetime.now().isoformat(),
            "validation": {
                "status": validated.get("status"),
                "quality_score": validated.get("quality_score"),
                "validated": validated.get("validated")
            },
            "workspace": {
                "cleaned_items": len(workspace.get("cleaned_data", [])),
                "status": workspace.get("status")
            },
            "output_files": [
                "auto_generated_doc.md",
                "summary_report.md",
                "metadata.json"
            ]
        }

        with open(path, "w") as f:
            json.dump(metadata, f, indent=2)

        return path

    def _format_strategic_section(self, validated):
        """Format the strategic section of documentation."""
        data = validated.get("data", {})
        strategic = data.get("indexed_data", {}).get("strategic", {})

        if not strategic:
            return "*No strategic data available*"

        sections = []
        if strategic.get("roadmap"):
            sections.append("### Roadmap\n")
            for key, value in strategic["roadmap"].items():
                sections.append(f"- **{key}:** {value}")

        return "\n".join(sections) if sections else "*Strategic data pending*"

    def _format_organization_section(self, validated):
        """Format the organization section."""
        data = validated.get("data", {})
        tags = data.get("tags", [])

        if not tags:
            return "*No tags available*"

        return "**Tags:** " + ", ".join(tags)

    def _format_validation_section(self, validated):
        """Format the validation section."""
        issues = validated.get("issues", [])

        if not issues:
            return "✅ All validation checks passed successfully."

        return "**Issues Found:**\n" + "\n".join(
            f"- {issue}" for issue in issues)

    def _format_recommendations(self, validated):
        """Format the recommendations section."""
        recommendations = validated.get("recommendations", [])

        if not recommendations:
            return "*No recommendations at this time.*"

        return "\n".join(f"- {rec}" for rec in recommendations)

    def _format_strategic_summary(self, indexed_data):
        """Format strategic summary for the report."""
        strategic = indexed_data.get("strategic", {})

        if not strategic:
            return "*No strategic data processed*"

        items = []
        for key in ["roadmap", "gtm", "competitive"]:
            if strategic.get(key):
                items.append(f"- **{key.upper()}:** Available")

        return "\n".join(items) if items else "*Processing...*"
